"use client";

import Link from "next/link";
import { useState, useEffect } from "react";
import { Check, Bot, Zap, Shield, Sparkles, PenTool, LayoutTemplate, Megaphone, Share2, Globe, Cpu, ChevronDown, ChevronUp, Copy, RefreshCw, Star } from "lucide-react";
import SmartStartButton from "@/components/smart-start-button";

// --- INTERACTIVE DEMO DATA ---
const DEMO_STEPS = [
  { id: 1, label: "Basic Info", desc: "Describe what you want to write about..." },
  { id: 2, label: "Title Selection", desc: "Select the best title generated by AI..." },
  { id: 3, label: "Content Outline", desc: "Edit and arrange your article structure..." },
  { id: 4, label: "Content Writing", desc: "Watch the AI write your content..." },
  { id: 5, label: "Final Content", desc: "Review and export your masterpiece." }
];

export default function LandingPage() {
  // --- STATE FOR INTERACTIVE DEMO ---
  const [activeStep, setActiveStep] = useState(1);
  const [isAutoPlaying, setIsAutoPlaying] = useState(true);

  // Auto-play the demo
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isAutoPlaying) {
      interval = setInterval(() => {
        setActiveStep((prev) => (prev === 5 ? 1 : prev + 1));
      }, 4000); // Change step every 4 seconds
    }
    return () => clearInterval(interval);
  }, [isAutoPlaying]);

  const handleStepClick = (stepId: number) => {
    setActiveStep(stepId);
    setIsAutoPlaying(false); // Stop auto-play if user interacts
  };

  return (
    <div className="flex min-h-screen flex-col font-sans bg-white text-slate-900 overflow-x-hidden">
      
      {/* --- HEADER --- */}
      <header className="px-6 h-20 flex items-center justify-between sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-100">
        <div className="flex items-center gap-2 font-bold text-2xl text-slate-900 tracking-tight">
          <div className="text-blue-600">
            <Bot className="h-8 w-8" />
          </div>
          Atom<span className="text-blue-600">Writer</span> Clone
        </div>
        <nav className="hidden md:flex gap-8 text-sm font-semibold text-slate-600">
          <a href="#features" className="hover:text-blue-600 transition-colors">Features</a>
          <a href="#how-it-works" className="hover:text-blue-600 transition-colors">How It Works</a>
          <a href="#pricing" className="hover:text-blue-600 transition-colors">Pricing</a>
          <a href="#faq" className="hover:text-blue-600 transition-colors">FAQ</a>
        </nav>
        <div className="flex gap-4 items-center">
          <Link href="/auth" className="hidden sm:block">
             <button className="px-4 py-2 text-sm font-bold text-slate-600 hover:text-blue-600 transition-colors">Log in</button>
          </Link>
          <SmartStartButton text="Try Solidwriter Free" className="!px-6 !py-2.5 !text-sm !shadow-none !bg-blue-600 !text-white hover:!bg-blue-700 !rounded-lg" />
        </div>
      </header>

      {/* --- HERO SECTION --- */}
      <section className="pt-24 pb-16 px-6 text-center bg-white">
        <div className="max-w-5xl mx-auto space-y-6 animate-in fade-in slide-in-from-bottom-8 duration-700">
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-slate-900 leading-[1.1]">
            Write Better Content<br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">With AI That Understands Your Style</span>
          </h1>
          
          <p className="text-xl text-slate-500 max-w-3xl mx-auto leading-relaxed font-medium">
            Solidwriter combines powerful AI with intuitive tools to help you create engaging content faster than ever before - without losing your unique voice.
          </p>
          
          <div className="flex flex-col sm:flex-row justify-center gap-4 pt-8">
            <SmartStartButton text="Start Free Trial" className="!bg-blue-600 !text-white hover:!bg-blue-700 !px-10 !py-4 !text-lg !rounded-lg !shadow-xl shadow-blue-200" />
            <a href="#how-it-works">
                <button className="w-full sm:w-auto px-10 py-4 rounded-lg text-lg font-bold bg-white text-slate-700 hover:bg-slate-50 transition-all flex items-center justify-center gap-2 shadow-sm border border-slate-200">
                    See How It Works
                </button>
            </a>
          </div>
        </div>
      </section>

      {/* --- INTERACTIVE DEMO (THE ATOMWRITER CLONE PART) --- */}
      <section id="how-it-works" className="py-16 px-4 bg-white">
        <div className="max-w-6xl mx-auto bg-white rounded-3xl shadow-2xl border border-slate-100 overflow-hidden ring-1 ring-slate-100">
            
            {/* Header of Demo Card */}
            <div className="p-8 border-b border-slate-100 bg-white">
                <div className="flex items-center gap-2 mb-2">
                    <Sparkles className="h-5 w-5 text-yellow-500" fill="currentColor"/>
                    <h3 className="font-bold text-xl text-slate-900">Step by Step Content Builder</h3>
                </div>
                <p className="text-slate-500">Create amazing content in 5 simple steps.</p>
            </div>

            {/* Stepper Navigation */}
            <div className="px-8 py-6 bg-slate-50/50 border-b border-slate-100 overflow-x-auto">
                <div className="flex justify-between min-w-[600px] relative">
                    {/* Connecting Line */}
                    <div className="absolute top-4 left-0 w-full h-0.5 bg-slate-200 -z-0"></div>
                    
                    {DEMO_STEPS.map((step) => (
                        <button 
                            key={step.id} 
                            onClick={() => handleStepClick(step.id)}
                            className={`relative z-10 flex flex-col items-center gap-3 group focus:outline-none`}
                        >
                            <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 ${
                                activeStep >= step.id 
                                ? 'bg-slate-900 text-white shadow-lg scale-110' 
                                : 'bg-white text-slate-400 border-2 border-slate-200'
                            }`}>
                                {step.id}
                            </div>
                            <span className={`text-xs font-bold uppercase tracking-wider transition-colors ${
                                activeStep === step.id ? 'text-slate-900' : 'text-slate-400'
                            }`}>
                                {step.label}
                            </span>
                        </button>
                    ))}
                </div>
            </div>

            {/* Dynamic Screen Content */}
            <div className="p-8 md:p-12 min-h-[400px] bg-slate-50 flex flex-col justify-center">
                
                {/* STEP 1: BASIC INFO */}
                {activeStep === 1 && (
                    <div className="max-w-3xl mx-auto w-full space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                        <div className="space-y-2">
                            <label className="text-sm font-bold text-slate-900">Content Description</label>
                            <div className="w-full h-14 bg-white border border-slate-200 rounded-lg p-4 text-slate-600 shadow-sm flex items-center">
                                Creating a comprehensive guide about budget-friendly travel tips an
                                <span className="w-0.5 h-5 bg-blue-600 animate-pulse ml-0.5"></span>
                            </div>
                        </div>
                        <div className="grid grid-cols-2 gap-6">
                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-900">Language</label>
                                <div className="w-full h-12 bg-white border border-slate-200 rounded-lg px-4 flex items-center justify-between text-slate-600 shadow-sm">
                                    English <ChevronDown className="h-4 w-4 opacity-50"/>
                                </div>
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-900">Keywords</label>
                                <div className="w-full h-12 bg-white border border-slate-200 rounded-lg px-4 flex items-center text-slate-600 shadow-sm">
                                    travel, budget, hacks
                                </div>
                            </div>
                        </div>
                        <div className="flex justify-end pt-4">
                            <div className="px-6 py-3 bg-slate-900 text-white rounded-lg text-sm font-bold shadow-md">Next Step</div>
                        </div>
                    </div>
                )}

                {/* STEP 2: TITLES */}
                {activeStep === 2 && (
                    <div className="max-w-3xl mx-auto w-full space-y-6 animate-in fade-in slide-in-from-right-4 duration-500">
                        <h3 className="text-lg font-bold text-center mb-4">Select a generated title</h3>
                        <div className="space-y-3">
                            <div className="p-4 bg-white border border-slate-200 rounded-lg shadow-sm hover:border-blue-500 cursor-pointer transition-all">
                                The Ultimate Guide to Budget Travel: See More, Spend Less
                            </div>
                            <div className="p-4 bg-blue-50 border-2 border-blue-600 rounded-lg shadow-md cursor-pointer flex justify-between items-center">
                                <span className="font-medium text-blue-900">How to Travel the World on a Shoestring Budget</span>
                                <Check className="h-5 w-5 text-blue-600"/>
                            </div>
                            <div className="p-4 bg-white border border-slate-200 rounded-lg shadow-sm hover:border-blue-500 cursor-pointer transition-all">
                                Budget Travel 101: Your Complete Money-Saving Guide
                            </div>
                        </div>
                        <div className="flex justify-end pt-4">
                            <div className="px-6 py-3 bg-slate-900 text-white rounded-lg text-sm font-bold shadow-md">Next Step</div>
                        </div>
                    </div>
                )}

                {/* STEP 3: OUTLINE */}
                {activeStep === 3 && (
                    <div className="max-w-3xl mx-auto w-full space-y-6 animate-in fade-in slide-in-from-right-4 duration-500">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg font-bold">Review Outline</h3>
                            <button className="text-blue-600 text-sm font-bold hover:underline">+ Add Section</button>
                        </div>
                        <div className="space-y-3">
                            {[
                                "Introduction: The Joy of Budget Travel",
                                "1. Smart Flight Booking Strategies",
                                "2. Finding Affordable Accommodation",
                                "3. Eating Like a Local (and Saving Money)",
                                "Conclusion: Start Your Adventure"
                            ].map((item, i) => (
                                <div key={i} className="flex items-center gap-3 p-3 bg-white border border-slate-200 rounded-lg shadow-sm">
                                    <div className="text-slate-300 cursor-move">:::</div>
                                    <div className="flex-1 font-medium text-slate-700">{item}</div>
                                    <div className="text-slate-400"><PenTool className="h-4 w-4"/></div>
                                </div>
                            ))}
                        </div>
                        <div className="flex justify-end pt-4">
                            <div className="px-6 py-3 bg-slate-900 text-white rounded-lg text-sm font-bold shadow-md">Next Step</div>
                        </div>
                    </div>
                )}

                {/* STEP 4: WRITING */}
                {activeStep === 4 && (
                    <div className="max-w-3xl mx-auto w-full space-y-6 animate-in fade-in duration-500">
                        <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-8 min-h-[300px] relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-full h-1 bg-blue-100">
                                <div className="h-full bg-blue-600 animate-[progress_2s_ease-in-out_infinite] w-1/3"></div>
                            </div>
                            <h1 className="text-3xl font-bold mb-6 text-slate-900">How to Travel the World on a Shoestring Budget</h1>
                            <div className="space-y-4 text-slate-600 leading-relaxed">
                                <p>Traveling the world is a dream for many, but the misconception that it requires a massive bank account often holds people back. The truth is, with the right strategies and a bit of flexibility, you can explore amazing destinations without breaking the bank.</p>
                                <p>In this guide, we'll uncover the secrets of budget travel...</p>
                                <p className="opacity-50">
                                    First, let's talk about flights. Being flexible with your dates can save you hundreds of dollars. Use tools like Skyscanner or Google Flights to find the cheapest months to fly...
                                    <span className="inline-block w-1.5 h-4 bg-blue-600 ml-1 animate-pulse"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                )}

                {/* STEP 5: FINAL */}
                {activeStep === 5 && (
                    <div className="max-w-3xl mx-auto w-full space-y-6 animate-in zoom-in-95 duration-500">
                        <div className="flex justify-between items-center">
                            <div className="flex gap-2">
                                <span className="px-3 py-1 bg-green-100 text-green-700 text-xs font-bold rounded-full">Saved</span>
                                <span className="px-3 py-1 bg-slate-100 text-slate-600 text-xs font-bold rounded-full">1,240 words</span>
                            </div>
                            <div className="flex gap-2">
                                <button className="px-4 py-2 border border-slate-200 rounded-lg text-sm font-bold text-slate-600 flex items-center gap-2 hover:bg-white"><Copy className="h-4 w-4"/> Copy</button>
                                <button className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-bold flex items-center gap-2 shadow-md hover:bg-blue-700">Export</button>
                            </div>
                        </div>
                        <div className="bg-white border border-slate-200 rounded-xl shadow-lg p-8 min-h-[300px]">
                            <h1 className="text-3xl font-bold mb-6 text-slate-900">How to Travel the World on a Shoestring Budget</h1>
                            <div className="space-y-4 text-slate-600 leading-relaxed">
                                <p>Traveling the world is a dream for many, but the misconception that it requires a massive bank account often holds people back. The truth is, with the right strategies and a bit of flexibility, you can explore amazing destinations without breaking the bank.</p>
                                <h2 className="text-xl font-bold text-slate-800 mt-6 mb-2">1. Smart Flight Booking Strategies</h2>
                                <p>First, let's talk about flights. Being flexible with your dates can save you hundreds of dollars. Use tools like Skyscanner or Google Flights to find the cheapest months to fly. Consider layovers as mini-adventures rather than inconveniences.</p>
                                <h2 className="text-xl font-bold text-slate-800 mt-6 mb-2">2. Finding Affordable Accommodation</h2>
                                <p>Hostels are the backpacker's best friend, but don't overlook alternatives like Couchsurfing or house-sitting...</p>
                            </div>
                        </div>
                        <div className="text-center pt-4">
                            <button onClick={() => {setActiveStep(1); setIsAutoPlaying(true);}} className="text-blue-600 font-bold hover:underline flex items-center justify-center gap-2">
                                <RefreshCw className="h-4 w-4"/> Replay Demo
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
      </section>

      {/* --- POWERFUL FEATURES SECTION --- */}
      <section className="py-24 px-6 bg-white text-center">
        <div className="max-w-6xl mx-auto">
            <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-4">
                Powerful Features To <br/>
                <span className="text-blue-600">Supercharge Your Writing</span>
            </h2>
            <p className="text-lg text-slate-500 max-w-2xl mx-auto mb-16">
                Our AI-powered tools help you create better content faster, without sacrificing quality or your unique voice.
            </p>

            <div className="grid md:grid-cols-3 gap-8">
                {[
                    { icon: <LayoutTemplate className="h-8 w-8 text-blue-600"/>, title: "Step-by-Step Builder", desc: "Create perfectly structured content with our guided process. Our AI analyzes your topic and creates the ideal framework." },
                    { icon: <Zap className="h-8 w-8 text-blue-600"/>, title: "One-Click Blog Wizard", desc: "Generate complete blog posts instantly with just one click. Provide a topic and let our AI do the heavy lifting." },
                    { icon: <Bot className="h-8 w-8 text-blue-600"/>, title: "AI Writing Assistant", desc: "Get real-time suggestions, grammar corrections, and style improvements as you write. It's like having a pro editor." },
                    { icon: <Globe className="h-8 w-8 text-blue-600"/>, title: "Multilingual Support", desc: "Reach a global audience by generating content in over 30 languages with native-level fluency." },
                    { icon: <Share2 className="h-8 w-8 text-blue-600"/>, title: "Social Media Repurposing", desc: "Turn your articles into LinkedIn posts, Twitter threads, and Instagram captions instantly." },
                    { icon: <Shield className="h-8 w-8 text-blue-600"/>, title: "Plagiarism Free", desc: "Our AI generates unique content every time. We ensure your content is original and SEO-ready." }
                ].map((feature, i) => (
                    <div key={i} className="bg-slate-50 p-8 rounded-2xl border border-slate-100 hover:shadow-lg hover:-translate-y-1 transition-all duration-300 text-left group">
                        <div className="w-14 h-14 bg-white rounded-xl flex items-center justify-center shadow-sm mb-6 border border-slate-100 group-hover:border-blue-200">
                            {feature.icon}
                        </div>
                        <h3 className="text-xl font-bold text-slate-900 mb-3">{feature.title}</h3>
                        <p className="text-slate-500 leading-relaxed">{feature.desc}</p>
                    </div>
                ))}
            </div>
        </div>
      </section>

      {/* --- TESTIMONIALS --- */}
      <section className="py-24 px-6 bg-slate-50">
        <div className="max-w-6xl mx-auto">
            <h2 className="text-3xl md:text-5xl font-extrabold text-center text-slate-900 mb-6">
                Trusted By <span className="text-blue-600">Thousands</span>
            </h2>
            <p className="text-lg text-slate-500 text-center max-w-2xl mx-auto mb-16">
                See what our customers are saying about how Solidwriter has transformed their content creation.
            </p>

            <div className="grid md:grid-cols-2 gap-8">
                {[
                    { name: "Sarah Johnson", role: "Content Marketing Manager", text: "Solidwriter has cut my content creation time in half. The AI understands my brand voice perfectly, and the blog wizard is a game-changer for my team's productivity.", img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=faces" },
                    { name: "Mark Williams", role: "SEO Specialist", text: "I've tried many AI writing tools, but Solidwriter is in a league of its own. The content it produces ranks incredibly well, and the step-by-step builder ensures everything is structured properly.", img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces" }
                ].map((testimonial, i) => (
                    <div key={i} className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 flex flex-col justify-between">
                        <div className="flex gap-1 mb-4">
                            {[1,2,3,4,5].map(s => <Star key={s} className="h-5 w-5 text-yellow-400 fill-current"/>)}
                        </div>
                        <p className="text-slate-600 text-lg italic mb-6">"{testimonial.text}"</p>
                        <div className="flex items-center gap-4">
                            <img src={testimonial.img} alt={testimonial.name} className="w-12 h-12 rounded-full object-cover" />
                            <div>
                                <h4 className="font-bold text-slate-900">{testimonial.name}</h4>
                                <p className="text-sm text-slate-500">{testimonial.role}</p>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
            
            <div className="mt-16 flex justify-center gap-12 text-center">
                <div>
                    <div className="text-4xl font-extrabold text-slate-900">93%</div>
                    <div className="text-sm text-slate-500 font-bold uppercase tracking-wide mt-1">Customer Satisfaction</div>
                </div>
                <div>
                    <div className="text-4xl font-extrabold text-slate-900">10M+</div>
                    <div className="text-sm text-slate-500 font-bold uppercase tracking-wide mt-1">Words Generated</div>
                </div>
                <div>
                    <div className="text-4xl font-extrabold text-slate-900">5,000+</div>
                    <div className="text-sm text-slate-500 font-bold uppercase tracking-wide mt-1">Active Users</div>
                </div>
            </div>
        </div>
      </section>

      {/* --- PRICING --- */}
      <section id="pricing" className="py-24 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
                <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-4">Choose Your <span className="text-blue-600">Perfect Plan</span></h2>
                <p className="text-xl text-slate-500">Choose the plan that works best for your needs, with no hidden fees.</p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
                 {[
                     {name: 'Basic', price: '$12', words: '25,000', popular: false},
                     {name: 'Professional', price: '$24', words: '100,000', popular: true},
                     {name: 'Business', price: '$72', words: 'Unlimited', popular: false}
                 ].map((plan) => (
                     <div key={plan.name} className={`relative bg-white p-8 rounded-2xl border transition-all flex flex-col ${plan.popular ? 'border-blue-600 shadow-2xl scale-105 z-10' : 'border-slate-200 shadow-sm'}`}>
                        {plan.popular && <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-blue-600 text-white text-xs font-bold px-4 py-1.5 rounded-full uppercase tracking-wider">Most Popular</div>}
                        
                        <h3 className="text-2xl font-bold text-slate-900">{plan.name}</h3>
                        <div className="my-4 flex items-baseline">
                            <span className="text-5xl font-extrabold tracking-tight text-slate-900">{plan.price}</span>
                            <span className="text-slate-500 font-medium ml-1">/mo</span>
                        </div>
                        <p className="text-sm text-slate-500 mb-8 pb-8 border-b border-slate-100">
                            {plan.name === 'Business' ? 'For agencies requiring maximum scale.' : 'Perfect for creators and small teams.'}
                        </p>
                        
                        <ul className="space-y-4 mb-8 flex-1">
                            <li className="flex gap-3 text-sm items-center text-slate-700"><div className="rounded-full bg-green-100 p-1"><Check className="h-3 w-3 text-green-600"/></div> {plan.words} Words / month</li>
                            <li className="flex gap-3 text-sm items-center text-slate-700"><div className="rounded-full bg-green-100 p-1"><Check className="h-3 w-3 text-green-600"/></div> Access to All Wizards</li>
                            <li className="flex gap-3 text-sm items-center text-slate-700"><div className="rounded-full bg-green-100 p-1"><Check className="h-3 w-3 text-green-600"/></div> 30+ Languages</li>
                            <li className="flex gap-3 text-sm items-center text-slate-700"><div className="rounded-full bg-green-100 p-1"><Check className="h-3 w-3 text-green-600"/></div> Priority Support</li>
                        </ul>
                        
                        <Link href="/pricing" className="block w-full">
                            <button className={`w-full py-4 rounded-xl font-bold transition-all shadow-sm ${
                                plan.popular 
                                    ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-blue-200' 
                                    : 'bg-white text-slate-700 border-2 border-slate-200 hover:border-blue-600 hover:text-blue-600'
                            }`}>
                                Start 7-Day Free Trial
                            </button>
                        </Link>
                    </div>
                 ))}
            </div>
        </div>
      </section>

      {/* --- FAQ SECTION --- */}
      <section id="faq" className="py-24 px-6 bg-slate-50">
        <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl md:text-5xl font-extrabold text-center text-slate-900 mb-16">
                Frequently Asked <span className="text-blue-600">Questions</span>
            </h2>
            
            <div className="space-y-4">
                {[
                    "How does the AI writing assistant work?",
                    "Can Solidwriter create content that sounds like me?",
                    "Is there a limit to how many words I can generate?",
                    "Is there a free trial available?"
                ].map((q, i) => (
                    <div key={i} className="bg-white rounded-xl border border-slate-200 overflow-hidden">
                        <button className="w-full flex justify-between items-center p-6 text-left font-bold text-slate-900 hover:bg-slate-50 transition-colors">
                            {q}
                            <ChevronDown className="h-5 w-5 text-slate-400"/>
                        </button>
                    </div>
                ))}
            </div>
        </div>
      </section>

      {/* --- FINAL CTA --- */}
      <section className="py-24 px-6 text-center bg-white">
        <div className="max-w-5xl mx-auto">
            <h2 className="text-4xl md:text-6xl font-extrabold mb-6 text-slate-900 leading-tight">Ready to <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">Transform Your Writing</span> with AI?</h2>
            <p className="text-xl text-slate-500 mb-10 max-w-2xl mx-auto">
                Join thousands of writers who are saving time and creating better content with Solidwriter.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
                <SmartStartButton text="Start Your Free Trial" className="!bg-blue-600 !text-white hover:!bg-blue-700 !px-12 !py-5 !text-xl !shadow-2xl shadow-blue-200" />
                <button className="px-12 py-5 rounded-full text-xl font-bold bg-white text-slate-700 border-2 border-slate-200 hover:border-slate-300 transition-all">Schedule a Demo</button>
            </div>
            <p className="mt-8 text-sm font-semibold text-slate-400 flex items-center justify-center gap-6">
                <span className="flex items-center gap-2"><Check className="h-4 w-4 text-green-500"/> Cancel anytime</span>
                <span className="flex items-center gap-2"><Check className="h-4 w-4 text-green-500"/> No setup fees</span>
            </p>
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="bg-slate-900 text-slate-400 py-16 px-6">
        <div className="max-w-6xl mx-auto grid md:grid-cols-4 gap-12 mb-12">
            <div className="col-span-1 md:col-span-1">
                <div className="flex items-center gap-2 font-bold text-2xl text-white mb-4">
                  <Bot className="h-8 w-8 text-blue-500" /> Solidwriter
                </div>
                <p className="text-sm leading-relaxed">
                    Powerful AI writing assistant that helps you create better content faster.
                </p>
            </div>
            <div>
                <h4 className="text-white font-bold mb-6">Product</h4>
                <ul className="space-y-4 text-sm">
                    <li><a href="#" className="hover:text-white transition-colors">Features</a></li>
                    <li><a href="#" className="hover:text-white transition-colors">Pricing</a></li>
                    <li><a href="#" className="hover:text-white transition-colors">Testimonials</a></li>
                </ul>
            </div>
            <div>
                <h4 className="text-white font-bold mb-6">Resources</h4>
                <ul className="space-y-4 text-sm">
                    <li><a href="#" className="hover:text-white transition-colors">Blog</a></li>
                    <li><a href="#" className="hover:text-white transition-colors">Community</a></li>
                    <li><a href="#" className="hover:text-white transition-colors">Help Center</a></li>
                </ul>
            </div>
            <div>
                <h4 className="text-white font-bold mb-6">Company</h4>
                <ul className="space-y-4 text-sm">
                    <li><Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link></li>
                    <li><Link href="/terms" className="hover:text-white transition-colors">Terms of Service</Link></li>
                    <li><Link href="/support" className="hover:text-white transition-colors">Contact Us</Link></li>
                </ul>
            </div>
        </div>
        <div className="max-w-6xl mx-auto pt-8 border-t border-slate-800 flex flex-col md:flex-row justify-between items-center text-xs">
            <div>© 2024 Solidwriter Inc. All rights reserved.</div>
        </div>
      </footer>
    </div>
  );
}