import { db } from "@/lib/db";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import Editor from "@/components/editor";

interface DocumentPageProps {
  params: {
    id: string;
  };
}

export default async function DocumentPage({ params }: DocumentPageProps) {
  const session = await getServerSession(authOptions);
  
  if (!session) {
    redirect("/auth");
  }

  // Fetch the document with the content generated by the Wizard
  const document = await db.document.findUnique({
    where: {
      id: params.id,
      // Ensure users can only see their own docs
      // userId: session.user.id (Add this check if you have the user ID available in session correctly)
    },
  });

  if (!document) {
    notFound();
  }

  return (
    <Editor 
      documentId={document.id}
      title={document.title}
      initialContent={document.content} // This passes the AI text to Tiptap
    />
  );
}